---
title: "Foreword"
---

This tutorial aims to give you the tools to easily and efficiently create, and maintain your own online portfolio.

This tutorial is divided in three chapters : 

1. The first chapter of this tutorial focuses on creating a simple workflow for the rest of our work.\
    We will use **Git**, **Github**, and **Visual Studio Code**.
2. The second capter of this tutorial focuses on the design of the website.\
    We will use **Quarto**.
3. The third and last chapter of this tutorial focuses on the publication of our website.\
    We will use **Github Pages**.

Usually, one should learn HTML5 and CSS to know a bit of Web development.
However, in the recent years, a lot of static website generator have emerged, that make the conception of websites easier.
Among the several static website generator, [Jekyll](https://jekyllrb.com/), [Zola](https://www.getzola.org/), [Hugo](https://gohugo.io/), and [Quarto](https://quarto.org/) can be cited, but they are far from being the only ones. This tutorial focuses on Quarto in the second chapter.

After having designed your website with a static website generator, we finally have to make it available to the world, i.e. publish it.
Several free hosting services exist, such as [Netlify](https://www.netlify.com/), [Quarto Pub](https://quartopub.com/), and [GitHub Pages](https://pages.github.com/), among other ones.
This tutorial focuses on GitHub Pages in the third chapter.

Now, in order to make the whole process easier and fluid, this tutorial first focuses on the establishment of a workflow using Visual Studio Code, Git and GitHub.
This workflow allows to make the second and third steps easier, and is also very useful if you are to work in collaborative projects in the future.
This is thus the first chapter of this tutorial.
